query getProject ($id: ID) {
  getProjects(id: $id) {
    name
    date
    dateIsApprox
    location
    description
    id
    storytellers {
      userId
      ... on UserInterface {
        firstname
        lastname
      }
    }
  }
}
