query GetNonprofit ($id: ID) {
  getNonprofit (id: $id) {
    name
    description
    contacts {
      phoneSecondary
    }
    causes {
      name
    }
    projects {
      name
      date
      dateIsApprox
    }
  }
}
